// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7yS02LsyZHTfgif5h6O71DghR630f_LE',
    appId: '1:1076376296371:web:2da0f7ade64d4ca60249c6',
    messagingSenderId: '1076376296371',
    projectId: 'sarasavi-learners-system',
    authDomain: 'sarasavi-learners-system.firebaseapp.com',
    storageBucket: 'sarasavi-learners-system.appspot.com',
    measurementId: 'G-G6RPVS1143',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF5RbNm8l0p1DIeWwhocoesnYQEGZD7z0',
    appId: '1:1076376296371:android:7b8042f47cc8b23b0249c6',
    messagingSenderId: '1076376296371',
    projectId: 'sarasavi-learners-system',
    storageBucket: 'sarasavi-learners-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXK6F0fBqe5hxHb06aNnSS9Tq3nNGzNWY',
    appId: '1:1076376296371:ios:3e2654eb33d0bb8b0249c6',
    messagingSenderId: '1076376296371',
    projectId: 'sarasavi-learners-system',
    storageBucket: 'sarasavi-learners-system.appspot.com',
    androidClientId: '1076376296371-aun2pa7poiuma2eqnh43pitdifg1kkt8.apps.googleusercontent.com',
    iosBundleId: 'com.example.cfSarasaviApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7yS02LsyZHTfgif5h6O71DghR630f_LE',
    appId: '1:1076376296371:web:d3f53296f65261950249c6',
    messagingSenderId: '1076376296371',
    projectId: 'sarasavi-learners-system',
    authDomain: 'sarasavi-learners-system.firebaseapp.com',
    storageBucket: 'sarasavi-learners-system.appspot.com',
    measurementId: 'G-D05W3BQJ25',
  );

}